name: 🕵️‍♂️ CarryFlix Sniper Engine

on:
  schedule:
    - cron: '*/30 * * * *' # Menjalankan radar otomatis setiap 30 Menit
  workflow_dispatch: # Mengizinkan Kapten menekan tombol eksekusi manual

jobs:
  scrape-carryflix:
    name: CarryFlix Interceptor # <-- Ini yang sebelumnya salah ketik
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Menarik Repositori Markas
        uses: actions/checkout@v4

      - name: ⚙️ Mempersenjatai Python (Mesin Inti)
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📦 Mengisi Amunisi Dependencies (Playwright)
        run: |
          python -m pip install --upgrade pip
          pip install playwright requests
          playwright install chromium

      - name: 🚀 Menerjunkan Tank Playwright (Menyadap Sinyal)
        run: python carryflix.py

      - name: 📤 Mengirim Ulang File M3U8 ke Markas Utama
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Mabes Enterprise Auto-Bot"
          git add CarryFlix_BoneTV.m3u8
          git commit -m "🔥 Auto-Update CarryFlix M3U8" || echo "Tidak ada perubahan jadwal."
          git push
